class EngineError(Exception): ...
class StartupError(EngineError): ...
class InvalidLanguageError(EngineError): ...
class InvalidAnswerError(EngineError): ...
class CantGoBackError(EngineError): ...
class SessionTimeoutError(EngineError): ...
class NetworkError(EngineError): ...
